name: Develop Branch

on:
  push:
    branches: [develop]

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Build project
        run: npm run build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  integration-tests:
    runs-on: ubuntu-latest
    needs: test-matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Test package import
        run: |
          # Test that the package can be imported in different ways
          echo "Testing CommonJS import..."
          node -e "const gonex = require('./dist/index.js'); console.log('CommonJS import successful')"

          echo "Testing ES module import..."
          node --input-type=module -e "import gonex from './dist/index.js'; console.log('ES module import successful')"

      - name: Run benchmarks
        run: npm run benchmark || echo "No benchmarks configured"

      - name: Generate documentation
        run: npm run docs || echo "Documentation generation failed"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: develop-artifacts
          path: |
            dist/
            coverage/
            docs/
          retention-days: 30

  notify:
    runs-on: ubuntu-latest
    needs: [test-matrix, integration-tests]
    if: always()

    steps:
      - name: Notify on success
        if: needs.test-matrix.result == 'success' && needs.integration-tests.result == 'success'
        run: |
          echo "✅ All tests passed on develop branch!"
          echo "Ready for merge to master."

      - name: Notify on failure
        if: needs.test-matrix.result == 'failure' || needs.integration-tests.result == 'failure'
        run: |
          echo "❌ Some tests failed on develop branch!"
          echo "Please fix the issues before merging to master."
          exit 1
