name: Pull Request Checks

on:
  pull_request:
    branches: [master, develop]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate

  bundle-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check bundle size
        run: |
          echo "Checking bundle size..."
          if [ -d "dist" ]; then
            echo "Dist folder size:"
            du -sh dist/
            echo "Individual file sizes:"
            find dist/ -type f -name "*.js" -exec du -h {} \;
          else
            echo "No dist folder found"
          fi

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run prettier check
        run: npx prettier --check src/**/*.ts

      - name: Check for TODO comments
        run: |
          echo "Checking for TODO comments..."
          if grep -r "TODO" src/ --include="*.ts"; then
            echo "Found TODO comments. Please address them before merging."
            exit 1
          fi
          echo "No TODO comments found."

      - name: Check for console.log statements
        run: |
          echo "Checking for console.log statements..."
          if grep -r "console\.log" src/ --include="*.ts"; then
            echo "Found console.log statements. Please remove them before merging."
            exit 1
          fi
          echo "No console.log statements found."
